### ISSUE TITLE
msm-stub does not send DELETE event after client end RTSP connection

### ISSUE THREAD

**Issue by cnguyen44** [media-streaming-mesh/msm-rtsp-stub#6]
<img width="1670" alt="Screen Shot 2022-09-12 at 11 48 27 AM" src="https://user-images.githubusercontent.com/15233376/189732440-ab3bca56-3213-477d-8ded-58df3bd62cb9.png">
Logs from msm-cp shows doesn't show DELETE event after client end RTSP connection.

Steps to reproduces:
- Start MSM
- End rtsp-client stream
- Logs msm-cp

**Comment by gilesheron** [comment]
think this is fixed in the latest msm-rtsp-stub
